let dados = [
  {
    imagem: "./img/labrador-retrivier.jfif",
    raca: "Labrador Retriever",
    descricao: "Cão de porte médio, pelagem curta e densa, muito inteligente e amigável.",
    utilizacao: "Companhia, caça, trabalho de assistência, guia para cegos.",
    link: "https://pt.wikipedia.org/wiki/Golden_retriever",
    tags: "labrador, retriever, cão d'água, companheiro, família, ativo, inteligente, obediência",
  },
  {
    imagem: "./img/pastor-alemao.jfif",
    raca: "Pastor Alemão",
    descricao: "Cão de porte grande, musculoso e inteligente, conhecido por sua lealdade e obediência.",
    utilizacao: "Guarda, polícia, trabalho de busca e resgate, companhia.",
    link: "https://pt.wikipedia.org/wiki/Pastor-alemão",
    tags: "pastor alemão, cão de guarda, proteção, polícia, exército, ágil, forte, leal",
  },
  {
    imagem: "./img/golden-retriever.jfif",
    raca: "Golden Retriever",
    descricao: "Cão de porte médio, pelagem longa e dourada, extremamente amigável e paciente.",
    utilizacao: "Companhia, caça, terapia, trabalho de assistência.",
    link: "https://pt.wikipedia.org/wiki/Labrador_retriever",
    tags: "golden retriever, retriever, dourado, amigável, paciente, terapia, caça, trabalho de assistência",
  },
  {
    imagem: "./img/bulldog-frances.jfif",
    raca: "Bulldog Francês",
    descricao: "Cão de pequeno porte, musculoso e brincalhão, com focinho achatado.",
    utilizacao: "Companhia, apartamento.",
    link: "https://pt.wikipedia.org/wiki/Buldogue_francês",
    tags: "bulldog francês, frenchie, achatado, brincalhão, companheiro, ronco",
  },
  {
    imagem: "./img/chihuahua.jfif",
    raca: "Chihuahua",
    descricao: "Cão de porte muito pequeno, alerta e vivaz, com grande personalidade.",
    utilizacao: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Chihuahua_(cão)",
    tags: "chihuahua, pequeno, mini, alerta, vivo, teimoso",
  },
  {
    imagem: "./img/beagle.jfif",
    raca: "Beagle",
    descricao: "Cão de médio porte, pelagem curta e tricolor, conhecido por seu olfato apurado.",
    utilizacao: "Caça, companhia.",
    link: "https://pt.wikipedia.org/wiki/Beagle",
    tags: "beagle, caça, farejador, brincalhão, amigável",
  },
  {
    raca: "Akita Inu",
    descricao: "Cão de porte grande, originário do Japão, conhecido por sua lealdade e independência.",
    imagem: "./img/akita-inu.jfif",
    utilizacao: "Companhia, guarda.",
    link: "https://pt.wikipedia.org/wiki/Akita_Inu",
    tags: "akita, japonês, leal, independente, guarda",
  },
  {
    raca: "Bichon Frisé",
    descricao: "Cão de pequeno porte, com pelagem branca e encaracolada, alegre e brincalhão.",
    imagem: "./img/bichon-frise.jfif",
    utilizacao: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Bichon_frisé",
    tags: "bichon frisé, branco, hipoalergênico, alegre, brincalhão",
  },
  {
    raca: "Border Collie",
    descricao: "Cão de porte médio a grande, extremamente inteligente e energético, utilizado em atividades de pastoreio.",
    imagem: "./img/border-collie.jfif",
    utilizacao: "Pastoreio, agility, obediência.",
    link: "https://pt.wikipedia.org/wiki/Border_collie",
    tags: "border collie, pastor, inteligente, ativo, energia",
  },
  {
    raca: "Bulldog Inglês",
    descricao: "Cão de porte médio, musculoso e braquicefálico, conhecido por sua natureza calma e amigável.",
    imagem: "./img/bulldog-ingles.jfif",
    utilizacao: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Buldogue",
    tags: "bulldog inglês, musculoso, braquiocefálico, calmo, companheiro",
  },
  {
    raca: "Corgi",
    descricao: "Cão de pequeno porte, com pernas curtas e corpo alongado, inteligente e ativo.",
    imagem: "./img/corgi.jfif",
    utilizacao: "Companhia, agility.",
    link: "https://pt.wikipedia.org/wiki/Welsh_corgi_pembroke",
    tags: "corgi, pernas curtas, rainha da Inglaterra, pastor, alegre",
  },
  {
    raca: "Dachshund",
    descricao: "Cão de pequeno porte, com corpo alongado e pernas curtas, conhecido por sua personalidade teimosa e corajosa.",
    imagem: "./img/dachshund.jfif",
    utilizacao: "Companhia, caça.",
    link: "https://pt.wikipedia.org/wiki/Dachshund",
    tags: "dachshund, salsicha, longo, caça, teimoso",
  },
  {
    raca: "Husky Siberiano",
    descricao: "Cão de porte médio a grande, com pelagem espessa e olhos azuis, conhecido por sua resistência e energia.",
    imagem: "./img/husky-siberiano.jfif",
    utilizacao: "Corrida de trenó, companhia.",
    link: "https://pt.wikipedia.org/wiki/Husky_siberiano",
    tags: "husky, siberiano, trenó, olhos azuis, ativo",
  },
  {
    raca: "Poodle",
    descricao: "Cão de diversas variedades (padrão, anão e toy), inteligente, elegante e hipoalergênico.",
    imagem: "./img/poodle.jfif",
    utilizacao: "Companhia, show.",
    link: "https://pt.wikipedia.org/wiki/Poodle",
    tags: "poodle, inteligente, hipoalergênico, água, corte de pelo",
  },
  {
    raca: "Rottweiler",
    descricao: "Cão de porte grande, forte e musculoso, utilizado como cão de guarda e trabalho.",
    imagem: "./img/rottweiler.jfif",
    utilizacao: "Guarda, proteção.",
    link: "https://pt.wikipedia.org/wiki/Rottweiler",
    tags: "rottweiler, guarda, forte, leal, protetor",
  },
  {
    raca: "Shih Tzu",
    descricao: "Cão de pequeno porte, com pelagem longa e sedosa, conhecido por sua natureza dócil e companheira.",
    imagem: "./img/shih-tzu.jfif",
    utilizacao: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Shih_Tzu",
    tags: "shih tzu, pequeno, longo, sedoso, companheiro",
  },
];
