let dados = [
  {
    imagem: "./img/labrador-retrivier.jfif",
    raca: "Labrador Retriever",
    descricao: "Cão de porte médio, pelagem curta e densa, muito inteligente e amigável.",
    utilidades: "Companhia, caça, trabalho de assistência, guia para cegos.",
    link: "https://pt.wikipedia.org/wiki/Golden_retriever",
    tags: "",
  },
  {
    imagem: "./img/pastor-alemao.jfif",
    raca: "Pastor Alemão",
    descricao: "Cão de porte grande, musculoso e inteligente, conhecido por sua lealdade e obediência.",
    utilidades: "Guarda, polícia, trabalho de busca e resgate, companhia.",
    link: "https://pt.wikipedia.org/wiki/Pastor-alemão",
    tags: "",
  },
  {
    imagem: "./img/golden-retriever.jfif",
    raca: "Golden Retriever",
    descricao: "Cão de porte médio, pelagem longa e dourada, extremamente amigável e paciente.",
    utilidades: "Companhia, caça, terapia, trabalho de assistência.",
    link: "https://pt.wikipedia.org/wiki/Labrador_retriever",
    tags: "",
  },
  {
    imagem: "./img/bulldog-frances.jfif",
    raca: "Bulldog Francês",
    descricao: "Cão de pequeno porte, musculoso e brincalhão, com focinho achatado.",
    utilidades: "Companhia, apartamento.",
    link: "https://pt.wikipedia.org/wiki/Buldogue_francês",
    tags: "",
  },
  {
    imagem: "./img/chihuahua.jfif",
    raca: "Chihuahua",
    descricao: "Cão de porte muito pequeno, alerta e vivaz, com grande personalidade.",
    utilidades: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Chihuahua_(cão)",
    tags: "",
  },
  {
    imagem: "./img/beagle.jfif",
    raca: "Beagle",
    descricao: "Cão de médio porte, pelagem curta e tricolor, conhecido por seu olfato apurado.",
    utilidades: "Caça, companhia.",
    link: "https://pt.wikipedia.org/wiki/Beagle",
    tags: "",
  },
  {
    raca: "Akita Inu",
    descricao: "Cão de porte grande, originário do Japão, conhecido por sua lealdade e independência.",
    imagem: "./img/akita-inu.jfif",
    utilidades: "Companhia, guarda.",
    link: "https://pt.wikipedia.org/wiki/Akita_Inu",
    tags: "",
  },
  {
    raca: "Bichon Frisé",
    descricao: "Cão de pequeno porte, com pelagem branca e encaracolada, alegre e brincalhão.",
    imagem: "./img/bichon-frise.jfif",
    utilidades: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Bichon_frisé",
    tags: "",
  },
  {
    raca: "Border Collie",
    descricao: "Cão de porte médio a grande, extremamente inteligente e energético, utilizado em atividades de pastoreio.",
    imagem: "./img/border-collie.jfif",
    utilidades: "Pastoreio, agility, obediência.",
    link: "https://pt.wikipedia.org/wiki/Border_collie",
    tags: "",
  },
  {
    raca: "Bulldog Inglês",
    descricao: "Cão de porte médio, musculoso e braquicefálico, conhecido por sua natureza calma e amigável.",
    imagem: "./img/bulldog-ingles.jfif",
    utilidades: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Buldogue",
    tags: "",
  },
  {
    raca: "Corgi",
    descricao: "Cão de pequeno porte, com pernas curtas e corpo alongado, inteligente e ativo.",
    imagem: "./img/corgi.jfif",
    utilidades: "Companhia, agility.",
    link: "https://pt.wikipedia.org/wiki/Welsh_corgi_pembroke",
    tags: "",
  },
  {
    raca: "Dachshund",
    descricao: "Cão de pequeno porte, com corpo alongado e pernas curtas, conhecido por sua personalidade teimosa e corajosa.",
    imagem: "./img/dachshund.jfif",
    utilidades: "Companhia, caça.",
    link: "https://pt.wikipedia.org/wiki/Dachshund",
    tags: "",
  },
  {
    raca: "Husky Siberiano",
    descricao: "Cão de porte médio a grande, com pelagem espessa e olhos azuis, conhecido por sua resistência e energia.",
    imagem: "./img/husky-siberiano.jfif",
    utilidades: "Corrida de trenó, companhia.",
    link: "https://pt.wikipedia.org/wiki/Husky_siberiano",
    tags: "",
  },
  {
    raca: "Poodle",
    descricao: "Cão de diversas variedades (padrão, anão e toy), inteligente, elegante e hipoalergênico.",
    imagem: "./img/poodle.jfif",
    utilidades: "Companhia, show.",
    link: "https://pt.wikipedia.org/wiki/Poodle",
    tags: "",
  },
  {
    raca: "Rottweiler",
    descricao: "Cão de porte grande, forte e musculoso, utilizado como cão de guarda e trabalho.",
    imagem: "./img/rottweiler.jfif",
    utilidades: "Guarda, proteção.",
    link: "https://pt.wikipedia.org/wiki/Rottweiler",
    tags: "",
  },
  {
    raca: "Shih Tzu",
    descricao: "Cão de pequeno porte, com pelagem longa e sedosa, conhecido por sua natureza dócil e companheira.",
    imagem: "./img/shih-tzu.jfif",
    utilidades: "Companhia.",
    link: "https://pt.wikipedia.org/wiki/Shih_Tzu",
    tags: "",
  },
];
